Update to dialog api
snipsco/snipsskills pull request #21
Opened 2017-11-22 12:49 UTC by yxdunc

2017-11-22 14:25 UTC, nebuto requested changes

2017-11-22 14:25 UTC, nebuto commented on snipsmanager/commands/install/skill.py
> +
Forgot to delete this ?

2017-11-22 14:25 UTC, nebuto commented on snipsmanager/commands/run.py
> +                    .strip()
@michaelfester Is it relevant to replace this variables in this context ? We added it because it's present also on the handle_notifications loop.

2017-11-22 14:25 UTC, nebuto commented on snipsmanager/utils/pip_installer.py
> +        print("this the log we are looking for: " + str(url_or_pip));
Haha, need to be removed ;)

2017-11-22 14:25 UTC, nebuto commented on snipsmanager/utils/snipsfile.py
> +            notifications.append(notification)
👍

2017-11-22 14:25 UTC, nebuto commented on snipsmanager/commands/run.py
> +
To cover our bases, I would add an error if for some reasons in the future we add a new dialogue event and forget to handle it here :
```
else:
    raise NotImplementedError(
            'Dialogue event unrecognised, please update handle_dialogue_events_async in run.py')
```

2017-11-22 14:42 UTC, yxdunc commented on snipsmanager/commands/install/skill.py
> +
Yop, on it

2017-12-06 09:33 UTC, anthonyray approved these changes
Looks good to me !

2017-12-06 09:44 UTC, nebuto commented
LGTM

2017-12-06 09:44 UTC, nebuto approved these changes

2017-12-13 13:24 UTC, nebuto commented
LGTM

2017-12-13 18:33 UTC, merged